//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HampesFrilansare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competence()
        {
            this.Skill = new HashSet<Skill>();
        }
    
        public int competenceID { get; set; }
        public Nullable<int> resumeID { get; set; }
        public string name { get; set; }
        public string category { get; set; }
    
        public virtual Resume Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skill { get; set; }
    }
}
