//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HampesFrilansare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int educationID { get; set; }
        public Nullable<int> resumeID { get; set; }
        public string school { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string subject { get; set; }
        public string degree { get; set; }
    
        public virtual Resume Resume { get; set; }
    }
}
