//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HampesFrilansare.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Freelancer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Freelancer()
        {
            this.LoginCredentials = new HashSet<LoginCredentials>();
        }
    
        public int freelancerID { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fyll i förnamn")]
        public string firstname { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Fyll i efternamn")]
        public string lastname { get; set; }
        public string phonenumber { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Fyll i en emailadress")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Fyll i en giltig emailadress")]
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public string birthplace { get; set; }
        public string nationality { get; set; }
        public Nullable<int> resumeID { get; set; }
    
        public virtual Resume Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginCredentials> LoginCredentials { get; set; }
    }
}
