//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HampesFrilansare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hampesfrilansdbEntities : DbContext
    {
        public hampesfrilansdbEntities()
            : base("name=hampesfrilansdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competence> Competence { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Driverslicence> Driverslicence { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<Freelancer> Freelancer { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Resume> Resume { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<LoginCredentials> LoginCredentials { get; set; }
    }
}
