//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HampesFrilansare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int skillID { get; set; }
        public Nullable<int> competenceID { get; set; }
        public string name { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual Competence Competence { get; set; }
    }
}
